CREATE TABLE Regle('numero' INT(300) , 'regleFR' TEXT(1000) , 'regleEN' TEXT(1000));



INSERT INTO Regle(1 , 'SUJET VERBE ADJECTIF' , 'SUJET VERBE ADJECTIF');

INSERT INTO Regle(2 , 'SUJET VERDE COD' , 'SUJET VERBE COD');

INSERT INTO Regle(3 , 'SUJET VERBE COI' , 'SUJET VERBE COI');
INSERT INTO Regle(4 , 'SUJET VERBE COD COI' , 'SUJET VERBE COD COI');
