CREATE TABLE Token('token' VARCHAR(255));



INSERT INTO Token(ADV_TEMPS);

INSERT INTO Token(ADV_LIEU);

INSERT INTO Token(PREP_LIEU);

INSERT INTO Token(ADV_MANIERE);

INSERT INTO Token(PREP_MANIERE);

INSERT INTO Token(ARTICLE);

INSERT INTO Token(NOM_COMMUN);

INSERT INTO Token(NOM_PROPRE);

INSERT INTO Token(ADJECTIF);

INSERT INTO Token(DE);

INSERT INTO Token(PRONOM);

INSERT INTO Token(VERBE);

INSERT INTO Token(PREP_A);

INSERT INTO Token(SUJET);

INSERT INTO Token(COD);

INSERT INTO Token(COI);
